import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { doc, setDoc, deleteDoc } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId:'t', firestore:{ rules: readFileSync(process.argv[2],'utf8'), host:'127.0.0.1', port:8080 }});
await env.withSecurityRulesDisabled(async ctx=>{ const d=ctx.firestore();
  await setDoc(doc(d,'users/A'),{displayName:'A'}); await setDoc(doc(d,'users/B'),{displayName:'B'});
  await setDoc(doc(d,'gameRecords/ga'),{uid:'A'}); await setDoc(doc(d,'userTsumeGoLogs/la'),{uid:'A'}); await setDoc(doc(d,'observationLogs/oa'),{uid:'A'});
  await setDoc(doc(d,'users/B/friends/A'),{uid:'A'}); });
const a=env.authenticatedContext('A').firestore(), c=env.authenticatedContext('C').firestore();
let ok=0,ng=0; const t=async(n,p)=>{try{await p;ok++;console.log('PASS',n)}catch(e){ng++;console.log('FAIL',n,e.message.slice(0,80))}};
await t('C cannot delete A profile', assertFails(deleteDoc(doc(c,'users/A'))));
await t('C cannot delete A gameRecord', assertFails(deleteDoc(doc(c,'gameRecords/ga'))));
await t('C cannot delete A tsume log', assertFails(deleteDoc(doc(c,'userTsumeGoLogs/la'))));
await t('C cannot delete A observation log', assertFails(deleteDoc(doc(c,'observationLogs/oa'))));
await t('A deletes own gameRecord', assertSucceeds(deleteDoc(doc(a,'gameRecords/ga'))));
await t('A deletes own tsume log', assertSucceeds(deleteDoc(doc(a,'userTsumeGoLogs/la'))));
await t('A deletes own observation log', assertSucceeds(deleteDoc(doc(a,'observationLogs/oa'))));
await t('A deletes mirror in B friends', assertSucceeds(deleteDoc(doc(a,'users/B/friends/A'))));
await t('A cannot delete B profile', assertFails(deleteDoc(doc(a,'users/B'))));
await t('A deletes own profile', assertSucceeds(deleteDoc(doc(a,'users/A'))));
console.log(`${ok} pass, ${ng} fail`); await env.cleanup(); process.exit(ng?1:0);
